Onion/Models/Tarefa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Onion.Models
{
    [Table("Tarefas")]
    public class Tarefa : BaseModel
    {
        public Tarefa()
        {
            Prioridade = 0;
            Estado = EstadoDaTarefa.A_FAZER;
        }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public string Descricao { get; set; }

        [Range(0, 10, ErrorMessage = "Deve ser de 0 a 10")]

        public int? Prioridade { get; set; }

        public EstadoDaTarefa Estado { get; set; }

        public void Avancar()
        {
            if (Estado == EstadoDaTarefa.FAZENDO)
                Estado = EstadoDaTarefa.CONCLUIDO;

            if (Estado == EstadoDaTarefa.A_FAZER)
                Estado = EstadoDaTarefa.FAZENDO;
        }

        public void Regredir()
        {
            if (Estado == EstadoDaTarefa.FAZENDO)
                Estado = EstadoDaTarefa.A_FAZER;

            if (Estado == EstadoDaTarefa.CONCLUIDO)
                Estado = EstadoDaTarefa.FAZENDO;
        }
    }

}

public enum EstadoDaTarefa
{
    A_FAZER, FAZENDO, CONCLUIDO
}

Onion/Controllers/TarefaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Onion.DAL;
using Onion.Models;

namespace Onion.Controllers
{
    public class TarefaController : Controller
    {
        private readonly ProjetoDAO _projetoDAO;
        private readonly TarefaDAO _tarefaDAO;
        public TarefaController(ProjetoDAO projetoDAO, TarefaDAO tarefaDAO)
        {
            _projetoDAO = projetoDAO;
            _tarefaDAO = tarefaDAO;
        }
        [HttpGet]
        public IActionResult Cadastrar(int IdProjeto)
        {
            ViewBag.Title = "Criar Tarefa";
            ViewBag.IdProjeto = IdProjeto;
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(Tarefa tarefa, int idProjeto)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.IdProjeto = idProjeto;
                return View(tarefa);
            }

            Projeto projeto = _projetoDAO.Buscar(idProjeto);
            projeto.AdicionarTarefa(tarefa);
            _projetoDAO.Alterar(projeto);

            return RedirectToAction("Detalhar", "Projeto", new { id = idProjeto });
        }

        public IActionResult Detalhar(int id)
        {
            Projeto projeto = _projetoDAO.Buscar(id);
            ViewBag.Title = projeto.Nome;
            return View(projeto);
        }

        public IActionResult CadastrarTarefa(Projeto projeto, Tarefa tarefa)
        {

            return RedirectToAction("Detalhar", "Projeto");
        }

        [HttpGet]
        public IActionResult EditarTarefa(int IdTarefa, int IdProjeto)
        {
            ViewBag.Title = "Editar Tarefa";
            ViewBag.IdProjeto = IdProjeto;
            return View(_tarefaDAO.Buscar(IdTarefa));
        }

        [HttpPost]
        public IActionResult EditarTarefa(Tarefa tarefa, int IdProjeto)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.IdProjeto = IdProjeto;
                return View(tarefa);
            }

            _tarefaDAO.Alterar(tarefa);

            return RedirectToAction("Detalhar", "Projeto", new { id = IdProjeto });
        }
    }
}

Onion/Views/Tarefa/Cadastrar.cshtml
@model Tarefa

<div class="container">

    <div class="row mt-4">

      <form asp-action="Cadastrar" asp-controller="Tarefa" method="post" class="w-100">
        <fieldset>
            <input name="idProjeto" value="@ViewBag.IdProjeto" type="hidden" />

            <legend>Nova Tarefa</legend>
            <div asp-validation-summary="ModelOnly"></div>
            
            <div id="Descricao" class="form-group">
                <label asp-for="Descricao">Descrição:</label>
                <input class="form-control" asp-for="Descricao" type="text" placeholder="Descrição" />
                <span class="text-danger" asp-validation-for="Descricao"></span>
            </div>
        
            <div id="Prioridade" class="form-group">
                <label asp-for="Prioridade">Prioridade (0-10):</label>
                <input class="form-control" asp-for="Prioridade" type="number" value="0" placeholder="Prioridade" />
                <span class="text-danger" asp-validation-for="Prioridade"></span>
            </div>

            <input type="submit" class="btn btn-info" value="Adicionar" />
        </fieldset>
      </form>  

    </div>

</div>

Onion/Views/Tarefa/EditarTarefa.cshtml
@model Tarefa

<div class="container">

    <div class="row mt-4">

      <form asp-action="EditarTarefa" asp-controller="Tarefa" method="post" class="w-100">
        <fieldset>
            <input name="idProjeto" value="@ViewBag.IdProjeto" type="hidden" />
            <input asp-for="Id" type="hidden" />
            <input asp-for="Estado" type="hidden" />

            <legend>Nova Tarefa</legend>
            <div asp-validation-summary="ModelOnly"></div>
            
            <div id="Descricao" class="form-group">
                <label asp-for="Descricao">Descrição:</label>
                <input class="form-control" asp-for="Descricao" type="text" placeholder="Descrição" />
                <span class="text-danger" asp-validation-for="Descricao"></span>
            </div>
        
            <div id="Prioridade" class="form-group">
                <label asp-for="Prioridade">Prioridade (0-10):</label>
                <input class="form-control" asp-for="Prioridade" type="number" value="@Model.Prioridade" placeholder="Prioridade" />
                <span class="text-danger" asp-validation-for="Prioridade"></span>
            </div>

            <input type="submit" class="btn btn-info" value="Editar" />
        </fieldset>
      </form>  

    </div>

</div>